### ISSUE TITLE
MVP: User Auth

### ISSUE THREAD

**Issue by echurilov** [echurilov/eris#3]
User auth has:
- register (sign up)
- log in
- log out
- log in as demo user
- display errors on form submission
- displaying errors does not move around other elements
- clear errors on resubmit/moving between pages
- styling closely resembles actual site (for splash, login, & register pages)

**Comment by eshoule** [comment]
Looking good! Please address the unchecked issues, and then I can close this. 

# User Auth

## Functionality

- [x] The main button with logo should link to `/`
* When I click on the logo from the login/signup pages it does not bring me back to the splash /.

- [x] Has working demo login
* The demo login button works from the splash page, but not from the login page.

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
* I can sign up with a different email, but the same username.
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

**Comment by echurilov** [comment]
- Added link to logos on `/login` and `/register` 
- Uncommented `handleDemo` for `/login` (whoops)
- Where is the link I should remove? I'm not sure which you mean
- Being able to sign in with a different email and the same username is working as intended; Discord requires unique emails but allows users to have the same username (it assigns them an ID number to disambiguate)

**Comment by eshoule** [comment]
Good job!
